export const metadata = {
  title: 'Next.js',
  description: 'Generated by Next.js',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="en">
      <body>
        <header style={{ backgroundColor: "lightblue", padding: "1rem", }}>
          <p>This is my header</p>

        </header>
        {children}
      </body>
      <footer style={{ backgroundColor: "ghostwhite", padding: "1rem", }}>
        <p style={{ fontSize: "2rem", fontFamily: "sans-serif" }}>This is my footer</p>
      </footer>
    </html>
  )
}
